apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: firstangularapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        label-key : label-value  
    spec:
      containers:
        - name: dockerapp
          image: mohsindocker/dockerspp
          imagePullPolicy: Always
          ports:
          - containerPort: 80